name: syntax-check-39.yml

on:
  pull_request:
    branches: ["main"]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Python 3.9
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # Syntax check
      - name: Run syntax check
        run: |
          python -m compileall -q .